### ISSUE TITLE
使い方について

### ISSUE THREAD

**Issue by newburu** [dosacode/tenga#4]
こんにちは＆初めましての方は初めまして  にゅ〜ぶるです。

このリポジトリ教えて貰ったんで、コードレビューとかissueフォローしようと思ったんですが
既に何人の方がいらっしゃるようで、何かルール決まってますか？

見た感じ、ソース内に「わからない」とあれば、issue作って説明する？

のかな？と思いましたが、この「わからない」が、メモなのかヘルプなのかも分からないので、何でもフォロー出来ないなぁと思ったり…💦

issueとして上がってきたら、それにフォローするとか
何かルールあると有難いのですが…

**Comment by cresta522** [comment]
んー、特に決まってはないですね

私は直接なり何かしら連絡きたらここ見てissue投げてます

**Comment by newburu** [comment]
連絡あれば、のトリガーがあるんであれば、それで問題ないですかね。

こっちから状況分からず、あーだこーだ言いたくないだけなので、なにかトリガーあると嬉しいなと思ったので！

**Comment by dosacode** [comment]
ここに返事書けばいいの？
えーと、じゃあ私が聞きたいことあれば直接連絡して、答えてもらう、でいいのかな？？
なんかすまん。

**Comment by cresta522** [comment]
こんな大事になると思わなんだ

聞きたいことあれば直接でいいと思うよ

コードレビューも私は手が空いたときのみなので

**Comment by newburu** [comment]
困ってるのかどうかが知りたいだけで、そのトリガー欲しいなと思っただけなので、連絡取り合ってるなら大丈夫です。

私も何かあれば、連絡もらえれば見に来ますね。
